title: Kip's Page
author: Christopher Hetterich
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my test site. I am trying to get used to creating and editing pages.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
